### PR TITLE
WIP - Add initial ventura_upgrade_supported fact

### PR DESCRIPTION
**Pull request by rickheil**
Adds an initial ventura_upgrade_supported fact - sharing here in a PR so folks can use it during the beta, but should wait until RCs or .0 release to merge so we can compare any last minute device compatibility updates.

### CODE REVIEW

**Comment by erikng** [comment]
I believe this list is incomplete. Using this logic recreated in another tool, all of our arm64 macs aren't in any of these lists. Perhaps this dist is intel only?

**Comment by erikng** [comment]
```
ls -a -1 /UniversalMac_13.0_22A5286j_Restore
.
..
022-13374-062.dmg
078-20356-067.dmg
078-20417-067.dmg
078-20439-050.dmg
078-20441-067.dmg
078-37309-039.dmg
AppleDiagnostics.dmg
BootabilityBundle
BridgeVersion.bin
BridgeVersion.plist
BuildManifest.plist
EFI
EmbeddedOSFirmware.pkg
Firmware
PlatformSupport.plist
Restore.plist
RestoreVersion.plist
SystemVersion.plist
kernelcache.release.mac13g
kernelcache.release.mac13j
kernelcache.release.mac14g
kernelcache.release.vma2
usr
```

looks like there is a `Restore.plist` file with more information

towards the bottom

```xml

	<key>ProductBuildVersion</key>
	<string>22A5286j</string>
	<key>ProductVersion</key>
	<string>13.0</string>
	<key>SupportedProductTypeIDs</key>
	<dict>
		<key>DFU</key>
		<array>
			<integer>134242304</integer>
			<integer>167796737</integer>
			<integer>201351170</integer>
			<integer>604012803</integer>
			<integer>67133441</integer>
			<integer>167796736</integer>
			<integer>134242305</integer>
			<integer>570458371</integer>
			<integer>671121667</integer>
			<integer>704676114</integer>
			<integer>704676099</integer>
			<integer>671121682</integer>
			<integer>637567235</integer>
			<integer>536935936</integer>
		</array>
		<key>Recovery</key>
		<array>
			<integer>134242304</integer>
			<integer>167796737</integer>
			<integer>201351170</integer>
			<integer>604012803</integer>
			<integer>67133441</integer>
			<integer>167796736</integer>
			<integer>134242305</integer>
			<integer>570458371</integer>
			<integer>671121667</integer>
			<integer>704676114</integer>
			<integer>704676099</integer>
			<integer>671121682</integer>
			<integer>637567235</integer>
			<integer>536935936</integer>
		</array>
	</dict>
	<key>SupportedProductTypes</key>
	<array>
		<string>iMac21,1</string>
		<string>MacBookAir10,1</string>
		<string>iMac21,2</string>
		<string>VirtualMac2,1</string>
		<string>Macmini9,1</string>
		<string>Mac13,2</string>
		<string>Mac13,1</string>
		<string>MacBookPro17,1</string>
		<string>MacBookPro18,4</string>
		<string>Mac14,2</string>
		<string>MacBookPro18,2</string>
		<string>MacBookPro18,3</string>
		<string>Mac14,7</string>
		<string>MacBookPro18,1</string>
	</array>
	
```

**Comment by erikng** [comment]
https://gist.github.com/erikng/b1acc0e07f510f9378f6f78f3d7a7342 so far is working really well for me. We have over 20,000 machines passing.

**Comment by poundbangbash** [comment]
I didn't realize y'all had this started already. 
I came up with my own similar to what you found but just using the modelIDs.
https://github.com/poundbangbash/munki-facts/blob/add_ventura_upgrade_supported/facts/ventura_upgrade_supported.py

Combining, sorting, and de-duping values from the following files result in a list of supported models 
- 'SupportedProductTypes' from 42e79bd54bb7295a5b729d32cb2493217f5d88f0/AssetData/boot/Restore.plist
- 'SupportedModelProperties' from 42e79bd54bb7295a5b729d32cb2493217f5d88f0/AssetData/boot/PlatformSupport.plist

That ends up with a list like what Erik's gist has, too.

**Pull request closed without merging**
